<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="2"
            failures="1"
            tests="3">

  <testsuite name="tests.connexion"
    errors="2" failures="1" hostname="" id="" package="connexion" skipped="0"
    tests="3" time="33.14" timestamp="">
  
    <testcase name="Création de la salle par remplissage des champs" classname="tests.connexion" time="4.849" assertions="0">
    </testcase>
  
    <testcase name="Connexion à une salle" classname="tests.connexion" time="5.969" assertions="1">  <failure message="Testing if element&#39;s &lt;#active-users&gt; inner text equals &#39;3 actifs&#39; in 5000ms - expected &#34;equals &#39;3 actifs&#39;&#34; but got: &#34;1 actifs&#34; (5301ms)">    at DescribeInstance.&lt;anonymous&gt; (U:\Projet IFT729\UDS-IFT729-Projet\tests\connexion.js:41:26)</failure>

    
    </testcase>
  
    <testcase name="Multiple connexions à une salle" classname="tests.connexion" time="5.752" assertions="0">
    <error type="error"><![CDATA[
    Error
    at DescribeInstance.&lt;anonymous&gt; (U:\Projet IFT729\UDS-IFT729-Projet\tests\connexion.js:60:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ]]></error>
    
    </testcase>
  

  
    <system-err>
       TimeoutError
   Wait timed out after 5189ms
 TimeoutError
   Error while running &#34;waitUntil&#34; command: [TimeoutError] Wait timed out after 5189ms

    Error location:
    U:\Projet IFT729\UDS-IFT729-Projet\tests\connexion.js:60
    –––––––––––––––––––––––––––––––––––––––––––––––––––––––
     58 |          await browser
     59 |           .navigateTo(&#39;http://localhost:3000&#39;);
     60 |           await browser.waitUntil(async function () { 
     61 |             const windowHandles = await browser.window.getAllHandles();
     62 |       
    –––––––––––––––––––––––––––––––––––––––––––––––––––––––

    </system-err>
  

    

  
  </testsuite>
</testsuites>
